/*
Impart Security v0 REST API

Imparts v0 REST API.

API version: 0.0.0
Contact: support@impart.security
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the RulesTestCaseRunPostBodyDisabledOverridesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RulesTestCaseRunPostBodyDisabledOverridesInner{}

// RulesTestCaseRunPostBodyDisabledOverridesInner struct for RulesTestCaseRunPostBodyDisabledOverridesInner
type RulesTestCaseRunPostBodyDisabledOverridesInner struct {
	RuleId               *string `json:"rule_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RulesTestCaseRunPostBodyDisabledOverridesInner RulesTestCaseRunPostBodyDisabledOverridesInner

// NewRulesTestCaseRunPostBodyDisabledOverridesInner instantiates a new RulesTestCaseRunPostBodyDisabledOverridesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRulesTestCaseRunPostBodyDisabledOverridesInner() *RulesTestCaseRunPostBodyDisabledOverridesInner {
	this := RulesTestCaseRunPostBodyDisabledOverridesInner{}
	return &this
}

// NewRulesTestCaseRunPostBodyDisabledOverridesInnerWithDefaults instantiates a new RulesTestCaseRunPostBodyDisabledOverridesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRulesTestCaseRunPostBodyDisabledOverridesInnerWithDefaults() *RulesTestCaseRunPostBodyDisabledOverridesInner {
	this := RulesTestCaseRunPostBodyDisabledOverridesInner{}
	return &this
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *RulesTestCaseRunPostBodyDisabledOverridesInner) GetRuleId() string {
	if o == nil || IsNil(o.RuleId) {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RulesTestCaseRunPostBodyDisabledOverridesInner) GetRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RuleId) {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *RulesTestCaseRunPostBodyDisabledOverridesInner) HasRuleId() bool {
	if o != nil && !IsNil(o.RuleId) {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *RulesTestCaseRunPostBodyDisabledOverridesInner) SetRuleId(v string) {
	o.RuleId = &v
}

func (o RulesTestCaseRunPostBodyDisabledOverridesInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RulesTestCaseRunPostBodyDisabledOverridesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RuleId) {
		toSerialize["rule_id"] = o.RuleId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RulesTestCaseRunPostBodyDisabledOverridesInner) UnmarshalJSON(data []byte) (err error) {
	varRulesTestCaseRunPostBodyDisabledOverridesInner := _RulesTestCaseRunPostBodyDisabledOverridesInner{}

	err = json.Unmarshal(data, &varRulesTestCaseRunPostBodyDisabledOverridesInner)

	if err != nil {
		return err
	}

	*o = RulesTestCaseRunPostBodyDisabledOverridesInner(varRulesTestCaseRunPostBodyDisabledOverridesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "rule_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRulesTestCaseRunPostBodyDisabledOverridesInner struct {
	value *RulesTestCaseRunPostBodyDisabledOverridesInner
	isSet bool
}

func (v NullableRulesTestCaseRunPostBodyDisabledOverridesInner) Get() *RulesTestCaseRunPostBodyDisabledOverridesInner {
	return v.value
}

func (v *NullableRulesTestCaseRunPostBodyDisabledOverridesInner) Set(val *RulesTestCaseRunPostBodyDisabledOverridesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRulesTestCaseRunPostBodyDisabledOverridesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRulesTestCaseRunPostBodyDisabledOverridesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRulesTestCaseRunPostBodyDisabledOverridesInner(val *RulesTestCaseRunPostBodyDisabledOverridesInner) *NullableRulesTestCaseRunPostBodyDisabledOverridesInner {
	return &NullableRulesTestCaseRunPostBodyDisabledOverridesInner{value: val, isSet: true}
}

func (v NullableRulesTestCaseRunPostBodyDisabledOverridesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRulesTestCaseRunPostBodyDisabledOverridesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
