/*
Impart Security v0 REST API

Imparts v0 REST API.

API version: 0.0.0
Contact: support@impart.security
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the ListPatchBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPatchBody{}

// ListPatchBody struct for ListPatchBody
type ListPatchBody struct {
	// The new name of the list.
	Name *string `json:"name,omitempty"`
	// The description of the list.
	Description NullableString `json:"description,omitempty"`
	// The items in the list.
	Add []ListItemsInner `json:"add,omitempty"`
	// Items to remove from the list.
	Remove []string `json:"remove,omitempty"`
	// The applied labels.
	Labels               []string `json:"labels,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListPatchBody ListPatchBody

// NewListPatchBody instantiates a new ListPatchBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPatchBody() *ListPatchBody {
	this := ListPatchBody{}
	return &this
}

// NewListPatchBodyWithDefaults instantiates a new ListPatchBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPatchBodyWithDefaults() *ListPatchBody {
	this := ListPatchBody{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ListPatchBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPatchBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ListPatchBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ListPatchBody) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListPatchBody) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPatchBody) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ListPatchBody) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ListPatchBody) SetDescription(v string) {
	o.Description.Set(&v)
}

// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ListPatchBody) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ListPatchBody) UnsetDescription() {
	o.Description.Unset()
}

// GetAdd returns the Add field value if set, zero value otherwise.
func (o *ListPatchBody) GetAdd() []ListItemsInner {
	if o == nil || IsNil(o.Add) {
		var ret []ListItemsInner
		return ret
	}
	return o.Add
}

// GetAddOk returns a tuple with the Add field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPatchBody) GetAddOk() ([]ListItemsInner, bool) {
	if o == nil || IsNil(o.Add) {
		return nil, false
	}
	return o.Add, true
}

// HasAdd returns a boolean if a field has been set.
func (o *ListPatchBody) HasAdd() bool {
	if o != nil && !IsNil(o.Add) {
		return true
	}

	return false
}

// SetAdd gets a reference to the given []ListItemsInner and assigns it to the Add field.
func (o *ListPatchBody) SetAdd(v []ListItemsInner) {
	o.Add = v
}

// GetRemove returns the Remove field value if set, zero value otherwise.
func (o *ListPatchBody) GetRemove() []string {
	if o == nil || IsNil(o.Remove) {
		var ret []string
		return ret
	}
	return o.Remove
}

// GetRemoveOk returns a tuple with the Remove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPatchBody) GetRemoveOk() ([]string, bool) {
	if o == nil || IsNil(o.Remove) {
		return nil, false
	}
	return o.Remove, true
}

// HasRemove returns a boolean if a field has been set.
func (o *ListPatchBody) HasRemove() bool {
	if o != nil && !IsNil(o.Remove) {
		return true
	}

	return false
}

// SetRemove gets a reference to the given []string and assigns it to the Remove field.
func (o *ListPatchBody) SetRemove(v []string) {
	o.Remove = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ListPatchBody) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPatchBody) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ListPatchBody) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *ListPatchBody) SetLabels(v []string) {
	o.Labels = v
}

func (o ListPatchBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPatchBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Add) {
		toSerialize["add"] = o.Add
	}
	if !IsNil(o.Remove) {
		toSerialize["remove"] = o.Remove
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListPatchBody) UnmarshalJSON(data []byte) (err error) {
	varListPatchBody := _ListPatchBody{}

	err = json.Unmarshal(data, &varListPatchBody)

	if err != nil {
		return err
	}

	*o = ListPatchBody(varListPatchBody)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "add")
		delete(additionalProperties, "remove")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListPatchBody struct {
	value *ListPatchBody
	isSet bool
}

func (v NullableListPatchBody) Get() *ListPatchBody {
	return v.value
}

func (v *NullableListPatchBody) Set(val *ListPatchBody) {
	v.value = val
	v.isSet = true
}

func (v NullableListPatchBody) IsSet() bool {
	return v.isSet
}

func (v *NullableListPatchBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPatchBody(val *ListPatchBody) *NullableListPatchBody {
	return &NullableListPatchBody{value: val, isSet: true}
}

func (v NullableListPatchBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPatchBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
