/*
Impart Security v0 REST API

Imparts v0 REST API.

API version: 0.0.0
Contact: support@impart.security
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RulesScripts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RulesScripts{}

// RulesScripts struct for RulesScripts
type RulesScripts struct {
	Items                []RulesScript  `json:"items"`
	Meta                 CollectionMeta `json:"meta"`
	AdditionalProperties map[string]interface{}
}

type _RulesScripts RulesScripts

// NewRulesScripts instantiates a new RulesScripts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRulesScripts(items []RulesScript, meta CollectionMeta) *RulesScripts {
	this := RulesScripts{}
	this.Items = items
	this.Meta = meta
	return &this
}

// NewRulesScriptsWithDefaults instantiates a new RulesScripts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRulesScriptsWithDefaults() *RulesScripts {
	this := RulesScripts{}
	return &this
}

// GetItems returns the Items field value
func (o *RulesScripts) GetItems() []RulesScript {
	if o == nil {
		var ret []RulesScript
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *RulesScripts) GetItemsOk() ([]RulesScript, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *RulesScripts) SetItems(v []RulesScript) {
	o.Items = v
}

// GetMeta returns the Meta field value
func (o *RulesScripts) GetMeta() CollectionMeta {
	if o == nil {
		var ret CollectionMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *RulesScripts) GetMetaOk() (*CollectionMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *RulesScripts) SetMeta(v CollectionMeta) {
	o.Meta = v
}

func (o RulesScripts) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RulesScripts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["meta"] = o.Meta

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RulesScripts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRulesScripts := _RulesScripts{}

	err = json.Unmarshal(data, &varRulesScripts)

	if err != nil {
		return err
	}

	*o = RulesScripts(varRulesScripts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRulesScripts struct {
	value *RulesScripts
	isSet bool
}

func (v NullableRulesScripts) Get() *RulesScripts {
	return v.value
}

func (v *NullableRulesScripts) Set(val *RulesScripts) {
	v.value = val
	v.isSet = true
}

func (v NullableRulesScripts) IsSet() bool {
	return v.isSet
}

func (v *NullableRulesScripts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRulesScripts(val *RulesScripts) *NullableRulesScripts {
	return &NullableRulesScripts{value: val, isSet: true}
}

func (v NullableRulesScripts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRulesScripts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
