/*
Impart Security v0 REST API

Imparts v0 REST API.

API version: 0.0.0
Contact: support@impart.security
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConnectorDestinations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorDestinations{}

// ConnectorDestinations struct for ConnectorDestinations
type ConnectorDestinations struct {
	// A list of connector destinations.
	Items []ConnectorDestination `json:"items"`
}

type _ConnectorDestinations ConnectorDestinations

// NewConnectorDestinations instantiates a new ConnectorDestinations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorDestinations(items []ConnectorDestination) *ConnectorDestinations {
	this := ConnectorDestinations{}
	this.Items = items
	return &this
}

// NewConnectorDestinationsWithDefaults instantiates a new ConnectorDestinations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorDestinationsWithDefaults() *ConnectorDestinations {
	this := ConnectorDestinations{}
	return &this
}

// GetItems returns the Items field value
func (o *ConnectorDestinations) GetItems() []ConnectorDestination {
	if o == nil {
		var ret []ConnectorDestination
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ConnectorDestinations) GetItemsOk() ([]ConnectorDestination, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ConnectorDestinations) SetItems(v []ConnectorDestination) {
	o.Items = v
}

func (o ConnectorDestinations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorDestinations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *ConnectorDestinations) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorDestinations := _ConnectorDestinations{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectorDestinations)

	if err != nil {
		return err
	}

	*o = ConnectorDestinations(varConnectorDestinations)

	return err
}

type NullableConnectorDestinations struct {
	value *ConnectorDestinations
	isSet bool
}

func (v NullableConnectorDestinations) Get() *ConnectorDestinations {
	return v.value
}

func (v *NullableConnectorDestinations) Set(val *ConnectorDestinations) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorDestinations) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorDestinations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorDestinations(val *ConnectorDestinations) *NullableConnectorDestinations {
	return &NullableConnectorDestinations{value: val, isSet: true}
}

func (v NullableConnectorDestinations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorDestinations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
