/*
Impart Security v0 REST API

Imparts v0 REST API.

API version: 0.0.0
Contact: support@impart.security
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the BasicError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BasicError{}

// BasicError struct for BasicError
type BasicError struct {
	// Output of the error message.
	Message string `json:"message"`
}

// NewBasicError instantiates a new BasicError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBasicError(message string) *BasicError {
	this := BasicError{}
	this.Message = message
	return &this
}

// NewBasicErrorWithDefaults instantiates a new BasicError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBasicErrorWithDefaults() *BasicError {
	this := BasicError{}
	return &this
}

// GetMessage returns the Message field value
func (o *BasicError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BasicError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BasicError) SetMessage(v string) {
	o.Message = v
}

func (o BasicError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BasicError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

type NullableBasicError struct {
	value *BasicError
	isSet bool
}

func (v NullableBasicError) Get() *BasicError {
	return v.value
}

func (v *NullableBasicError) Set(val *BasicError) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicError) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicError(val *BasicError) *NullableBasicError {
	return &NullableBasicError{value: val, isSet: true}
}

func (v NullableBasicError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
