/*
Impart Security v0 REST API

Imparts v0 REST API.

API version: 0.0.0
Contact: support@impart.security
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ConnectorTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorTypes{}

// ConnectorTypes struct for ConnectorTypes
type ConnectorTypes struct {
	// A list of connector types.
	Items []ConnectorType `json:"items"`
	Meta  CollectionMeta  `json:"meta"`
}

type _ConnectorTypes ConnectorTypes

// NewConnectorTypes instantiates a new ConnectorTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorTypes(items []ConnectorType, meta CollectionMeta) *ConnectorTypes {
	this := ConnectorTypes{}
	this.Items = items
	this.Meta = meta
	return &this
}

// NewConnectorTypesWithDefaults instantiates a new ConnectorTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorTypesWithDefaults() *ConnectorTypes {
	this := ConnectorTypes{}
	return &this
}

// GetItems returns the Items field value
func (o *ConnectorTypes) GetItems() []ConnectorType {
	if o == nil {
		var ret []ConnectorType
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ConnectorTypes) GetItemsOk() ([]ConnectorType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ConnectorTypes) SetItems(v []ConnectorType) {
	o.Items = v
}

// GetMeta returns the Meta field value
func (o *ConnectorTypes) GetMeta() CollectionMeta {
	if o == nil {
		var ret CollectionMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ConnectorTypes) GetMetaOk() (*CollectionMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ConnectorTypes) SetMeta(v CollectionMeta) {
	o.Meta = v
}

func (o ConnectorTypes) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["meta"] = o.Meta
	return toSerialize, nil
}

func (o *ConnectorTypes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectorTypes := _ConnectorTypes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectorTypes)

	if err != nil {
		return err
	}

	*o = ConnectorTypes(varConnectorTypes)

	return err
}

type NullableConnectorTypes struct {
	value *ConnectorTypes
	isSet bool
}

func (v NullableConnectorTypes) Get() *ConnectorTypes {
	return v.value
}

func (v *NullableConnectorTypes) Set(val *ConnectorTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorTypes(val *ConnectorTypes) *NullableConnectorTypes {
	return &NullableConnectorTypes{value: val, isSet: true}
}

func (v NullableConnectorTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
